### ISSUE TITLE
Error: Unable to process file command 'output' successfully

### ISSUE THREAD

**Issue by grainnemcknight** [isort/isort-action#57] opened 2022-10-26 09:32 UTC
Hey, using this action in our codebase and as of yesterday it has been failing to run with `Error: Unable to process file command 'output' successfully.` This is our set-up:
```
  isort:
    runs-on: ubuntu-latest
    name: isort
    steps:
      - uses: actions/checkout@v2
      - uses: isort/isort-action@master
        with:
          configuration: "black"
```
Running isort with the same configuration on our codebase locally works and returns no errors and when we reverted to `-uses: isort/isort-action@v1.0.0` it ran successfully. 
The issue appears to have appeared with[ this commit](https://github.com/isort/isort-action/commit/cad8d89379c2bacf535f8ba4e82ef33da20a644a)

**Comment by yogevyuval** [comment] 2022-10-28 17:54
@aljazkosir ?

**Comment by aljazkosir** [comment] 2022-10-28 20:55
I'm currently still using my forked branch with the original changes I made: https://github.com/aljazkosir/isort-action/commit/4633520ba77bc5e0840ff82d48e0a496a927884b and it works. Note the `${GITHUB_OUTPUT}"` vs `$GITHUB_ENV`
Someone changed my PR without proper testing. 

I can prepare the PR again to address that. But I can't promise I will be able to do that until Monday.

**Comment by yogevyuval** [comment] 2022-10-28 21:03
> I'm currently still using my forked branch with the original changes I made: [aljazkosir@4633520](https://github.com/aljazkosir/isort-action/commit/4633520ba77bc5e0840ff82d48e0a496a927884b) and it works. Note the `${GITHUB_OUTPUT}` vs `$GITHUB_ENV` Someone changed my PR without proper testing.
> 
> I think the issue lies with curly brackets around the `GITHUB_OUTPUT`, which should be `$GITHUB_OUTPUT` not `${GITHUB_OUTPUT}`.
> 
> I can prepare the PR again to address that. But I can't promise I will be able to do that until Monday.

Thanks, no rush!
Just wanted to make sure you see this because currently many people use this action without a pinned version, so their CI check is failing

**Comment by jamescurtin** [comment] 2022-10-29 21:49
The issue here wasn't related to GITHUB_OUTPUT vs. GITHUB_ENV--instead, the new method for storing outputs handles multi-line strings differently than the previous, deprecated version did (See [this StackOverflow post](https://stackoverflow.com/questions/74137120/how-to-fix-or-avoid-error-unable-to-process-file-command-output-successfully) for additional details).

Therefore, this change only failed when the plugin was invoked in such a way that the output contained a multiline string. The PR I submitted that will close this issue resolves this, and also adds a basic test suite to assert this behavior so there aren't regressions in the future.

**Closed** 2022-10-29 21:49 UTC
